### ISSUE TITLE
ReflectionUtility can't get cachedPtr on Android

### ISSUE THREAD

**Issue by cfoulston** [muckSponge/UnityAsync#4]
I assume that System.Linq.Expressions cannot be used on Android. But this is the error I get:

`Unable to create field getter for Object.m_CachedPtr; internal implementation may have changed.`

Changing the implementation of IsAlive to:

`[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static bool IsAlive(this Object o) => o != null;`

Does fix the issue. Not sure why you need to use `m_CachedPtr`?

Could be related: https://forum.unity.com/threads/are-c-expression-trees-or-ilgenerator-allowed-on-ios.489498/

**Comment by muckSponge** [comment]
Yeah, my guess is it's not going to work on IOS, but not sure about Android. I have never tested this on Android but your `IsAlive` change is a perfectly acceptable workaround which I'll probably work into the codebase for IOS. On Android it may just be that `m_CachedPointer` has a different internal name but having never tested on Android, I don't know what it may be.

Why do I use m_CachedPtr? `IsAlive` is invoked for every active awaiter, every frame. If we use the standard `Object != null` or `Object == true` comparison, Unity dips into native code, which impacts on performance. `m_CachedPtr` is cached in managed code so by checking that pointer, we save a (relatively speaking) expensive trip into native code.

Honestly, if you're not running 10,000+ awaiters simultaneously, it probably won't have any impact. This was mostly an optimisation to improve benchmark results so that I can say it is "x times faster than y".

**Comment by cfoulston** [comment]
Ok makes sense, I'll keep it as `o != null` for now. Not sure how I can find out if m_CachedPtr exits on Android. I'll also do some tests and see if it's just a Linq.Expressions issue as well

**Comment by muckSponge** [comment]
I ended up researching this a bit and it seems platforms which don't support JIT compilation won't work. I found [this comparison](https://docs.unity3d.com/Manual/ScriptingRestrictions.html), which highlights the platforms that use AOT compilation and it seems they're all IL2CPP platforms, so my IL2CPP workaround in 15ee6b1 should work. Android can be JIT (Mono) or AOT (IL2CPP). Will close thus but if you're still experiencing issues I'm happy to open again.
